# Generated by Django 4.0.2 on 2022-02-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('temp', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
    ]
