# Generated by Django 4.0.2 on 2022-02-11 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Weather',
        ),
    ]
