# Generated by Django 4.0.2 on 2022-02-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_city_weather_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='description',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='name',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temp',
        ),
    ]
