# Generated by Django 4.0.2 on 2022-02-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
