# Generated by Django 4.0.2 on 2022-02-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
