# Generated by Django 4.0.2 on 2022-03-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.IntegerField(default=1),
        ),
    ]
