# Generated by Django 4.0.2 on 2022-03-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_person_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.AddField(
            model_name='car',
            name='owner_phone',
            field=models.IntegerField(default=2249735, max_length=30),
            preserve_default=False,
        ),
    ]
