# Generated by Django 4.0.2 on 2022-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_car_photo_alter_car_owner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
